### ISSUE TITLE
What's the advantage of StringBuilders.jl over just building one form IOBuffer?

### ISSUE THREAD

**Issue by xiaodaigh** [davidanthoff/StringBuilders.jl#12]
Below is what I do to build a String. What's the advantage of using StringBuilders.jl? I think it's worth explaining in the README as that was my first question. 

```julia
io = IOBuffer()
write(io, "abc", "def")
String(take!(io)) # "abcdef"
```

**Comment by davidanthoff** [comment]
Just a different API that I find easier to deal with because it feels less low level. PRs with additional text for the README are welcome.
