### ISSUE TITLE
Multiple arguments 

### ISSUE THREAD

**Issue by yakir12** [davidanthoff/StringBuilders.jl#5]
Love this package. 
A cool feature and in line with how IO functions work ([performance tip](https://docs.julialang.org/en/stable/manual/performance-tips/#Avoid-string-interpolation-for-I/O-1)) it would be great if `append!` could accept multiple arguments:
Current behavior:
```julia
a = "a"
b = "b"
append!(o, "$a$b")
```
Better behavior:
```julia
a = "a"
b = "b"
append!(o, a, b)
```

**Comment by davidanthoff** [comment]
Yes, I agree! A PR would be welcome.

**Comment by yakir12** [comment]
Sheesh.. sorry for the mess... Anyways, one PR is for the tests and one for the actual code. Obviously the tests won't pass without first merging the actual code PR... Feel free to ignore it all if you feel uneasy.

**Comment by davidanthoff** [comment]
Thanks, much appreciated!
