### ISSUE TITLE
Depending on StringBuilders.jl

### ISSUE THREAD

**Issue by jlapeyre** [davidanthoff/StringBuilders.jl#8]
I started a project that depends  `StringBuilders.jl`. I often want the bare minimum functionality of a mutable string; just building it by appending. If this package disappears or is not maintained, no big deal, I will copy the code. I just want to let you know that someone is using it.

**Comment by davidanthoff** [comment]
Excellent! I have no plans to let it disappear, if anything I would hope that if folks like it it could be moved to base or stdlib.
